name: SDC DB Sync (Beta)
on:    
  workflow_call:
    inputs:
      INST_NAME:
        required: true
        type: string
    secrets:
      EC_GITHUB_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      INST_NAME:
        description: The name associated with the credential set for this instance.
        required: true
        default: sdcAdm
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: beta
    env:
      #AGENT_REV: "1.2-b.0.reiwa"
      AGENT_REV: "temp"
    steps:
      - uses: actions/checkout@v2
      - name: SDC DB Replication
        id: sdc-db-repl
        env:
          EC_AUTH_VALIDATE: oaep
          EC_PORT: ":17990"
          EC_SEED_HOST: "http://localhost:17790"
          EC_GITHUB_TOKEN: ${{ secrets.EC_GITHUB_TOKEN }}
          INST_NAME: ${{ inputs.INST_NAME || github.event.inputs.INST_NAME }}
          
        run: |    
          source <(wget -O - https://raw.githubusercontent.com/EC-Release/sdk/disty/scripts/cipher/crypto.sh)
          crdj=$(getCredJson "cred.json" "$EC_GITHUB_TOKEN")
          
          #get sdc adm cred
          LIC_ID=$(echo $crdj | jq -r ".${INST_NAME}.devId")
          CA_PPRS=$(echo $crdj | jq -r ".${INST_NAME}.ownerHash")          
          EC_SEED_NODE=$(echo $crdj | jq -r ".${INST_NAME}.instURL")  
          EC_OAUTH_FAIL_URL=$(echo $crdj | jq -r ".${INST_NAME}.failURL")  
          DB_NAME=$(echo $crdj | jq -r ".${INST_NAME}.db")
          INST_LOG=${INST_NAME}.log
          echo "LIC_ID:" $LIC_ID          
         
          getPublicCrt "$LIC_ID" "$EC_GITHUB_TOKEN" > ./tmp.cer          
          csr_id=$(getCsrId "./tmp.cer")
          echo "csr_id:" $csr_id
          getPrivateKey "$csr_id" "$EC_GITHUB_TOKEN" > ./tmp.key
          
          mkdir -p ./.ec ./dbs
         
          setDb "$DB_NAME" "$EC_GITHUB_TOKEN"
          tree ./
         
          docker run \
          --name refc \
          -e AGENT_REV=${AGENT_REV} \
          -e CA_PPRS=${CA_PPRS} \
          -e EC_AUTH_VALIDATE=${EC_AUTH_VALIDATE} \
          -e EC_OAUTH_FAIL_URL=${EC_OAUTH_FAIL_URL} \
          -e EC_PORT=${EC_PORT} \
          -e EC_PUBCRT=$(cat ./tmp.cer|base64 -w0) \
          -e EC_PVTKEY=$(cat ./tmp.key|base64 -w0) \
          -e EC_SEED_HOST=${EC_SEED_HOST} \
          -e EC_SEED_NODE=${EC_SEED_NODE} \
          -v $(pwd)/.ec/.db:/root/.ec/.db \
          -d ghcr.io/ec-release/sdc:1.2-b
          #-t ghcr.io/ec-release/oauth:v1.2beta | tee -a ${INST_LOG} >/dev/null
          
          sleep 15
          
          docker logs refc > ${INST_LOG}
          
          ls -al ./.ec/.db
          cp ./.ec/.db ./dbs/${DB_NAME}
          cp ${INST_LOG} ./dbs/${INST_LOG}
          
      - name: SDC DB Check-in
        id: sdc-db-check-in
        uses: ec-release/github-action-copy-files-folders-to-another-repos@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.EC_GITHUB_TOKEN }}
          GIT_USEREMAIL: EC.Bot@ge.com
          GIT_USERNAME: EC.Bot
        with:
          SOURCE_DIR: 'dbs'
          DESTINATION_REPOS_BRANCHES: 'github.com/EC-Release/data-storage.git:main'
          COMMIT_MESSAGE: 'SDC DB Check-in'
