name: Seeder DB Sync (Beta)
on:
  workflow_call:
    inputs:
      INST_NAME:
        required: true
        type: string
    secrets:
      EC_GITHUB_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      INST_NAME:
        description: The name associated with the credential set for this instance.
        required: true
        default: seederAdm
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: beta
    env:
      #AGENT_REV: "1.2-b.0.reiwa"
      AGENT_REV: "temp"
    steps:
      - uses: actions/checkout@v2
      - name: Seeder DB Replication
        id: sdr-db-repl
        env:
          EC_AGT_GRP: test-group
          EC_AGT_MODE: x:gateway
          EC_API_APP_NAME: ec
          EC_PORT: ":17990"
          EC_GITHUB_TOKEN: ${{ secrets.EC_GITHUB_TOKEN }}
          INST_NAME: ${{ inputs.INST_NAME || github.event.inputs.INST_NAME }}
        run: chmod +x ./seeder.sh && source ./seeder.sh          
           
      - name: Seeder DB Check-in
        id: sdr-db-check-in
        uses: ec-release/github-action-copy-files-folders-to-another-repos@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.EC_GITHUB_TOKEN }}
          GIT_USEREMAIL: EC.Bot@ge.com
          GIT_USERNAME: EC.Bot
        with:
          SOURCE_DIR: 'dbs'
          DESTINATION_REPOS_BRANCHES: 'github.com/EC-Release/data-storage.git:main'
          COMMIT_MESSAGE: 'Seeder DB Check-in'
