name: Scheduled DB Sync (Beta)
on:
  schedule:
    #NY 22:00pm
    - cron: '0 2 * * *'
    #- cron: '*/6 * * * *'
jobs:
  sdc-admin-dbsync:
    uses: EC-Release/ec2.x-ci/.github/workflows/dbsync-sdc.yml@main
    with:
      INST_NAME: sdcAdm
    secrets:
      EC_GITHUB_TOKEN: ${{ secrets.EC_GITHUB_TOKEN }}
  sdc-admin-backup-dbsync:
    uses: EC-Release/ec2.x-ci/.github/workflows/dbsync-sdc.yml@main
    with:
      INST_NAME: sdcAdmBkp
    secrets:
      EC_GITHUB_TOKEN: ${{ secrets.EC_GITHUB_TOKEN }}
  seeder-admin-dbsync:
    uses: EC-Release/ec2.x-ci/.github/workflows/dbsync-seeder.yml@main
    needs: [sdc-admin-dbsync]
    with:
      INST_NAME: seederAdm
    secrets:
      EC_GITHUB_TOKEN: ${{ secrets.EC_GITHUB_TOKEN }}
  seeder-admin-backup-dbsync:
    uses: EC-Release/ec2.x-ci/.github/workflows/dbsync-seeder.yml@main
    needs: [seeder-admin-dbsync]
    with:
      INST_NAME: seederAdmBkp
    secrets:
      EC_GITHUB_TOKEN: ${{ secrets.EC_GITHUB_TOKEN }}
  team-notification:
    needs: [sdc-admin-dbsync, seeder-admin-dbsync, seeder-admin-backup-dbsync]
    runs-on: ubuntu-latest
    environment: beta
    env:
      #AGENT_REV: "1.2-b.0.reiwa"
      AGENT_REV: "temp"
    steps:
      - uses: actions/checkout@v2
      - name: Notify Success of DB Sync on Schedule
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.ADM_EML_SVR }}
          server_port: 587
          username: ${{secrets.ADM_EML_USR}}
          password: ${{secrets.ADM_EML_PWD}}
          subject: EC-Release > Deployment CI > Scheduled Team DB Sync
          # Literal body:
          body: |
            ### Scheduled Team DB Sync
            Team DB Sync (SDC, Seeder) completed 

          # Read file contents as body:
          #attachments: ./../pkeys/${{env.EC_CSR_ID}}.key
          to: ec-research@ge.com
          from: EC.Bot <EC.Bot@DoNotReply.io>
          # Optional carbon copy recipients
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients
          #bcc: r2d2@example.com,hansolo@example.com
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
