name: mail test
on:
  workflow_dispatch:
jobs:
  
  team-notification:
    runs-on: ubuntu-latest
    environment: beta
    env:
      AGENT_REV: "temp"
    steps:
      - uses: actions/checkout@v2
      - name: Notify Success of DB Sync on Schedule
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.ADM_EML_SVR }}
          server_port: 587
          username: ${{secrets.ADM_EML_USR}}
          password: ${{secrets.ADM_EML_PWD}}
          subject: EC-Release > Deployment CI > Scheduled Team DB Sync
          # Literal body:
          body: |
            ### Scheduled Team DB Sync
            Team DB Sync (SDC, Seeder) completed 

          # Read file contents as body:
          #attachments: ./../pkeys/${{env.EC_CSR_ID}}.key
          to: ec-research@ge.com
          bcc: ${{secrets.ADM_BCC_EMAILS}}
          from: EC.Bot <EC.Bot@DoNotReply.io>
          # Optional carbon copy recipients
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients
          #bcc: r2d2@example.com,hansolo@example.com
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
